---
title: "Theory of use-resistance relationships over geographic scales"
author: "Scott Olesen"
---

```{r global_options, echo = FALSE}
knitr::opts_chunk$set(
  fig.width = 7, fig.height = 4, fig.path = 'fig/',
  dev = c('png', 'pdf'),
  echo = FALSE, warning = FALSE, message = FALSE,
  cache = TRUE, autodep = TRUE)

pdf.options(useDingbats = FALSE, useKerning = FALSE)

library(kableExtra)
options(knitr.table.format = 'pandoc')
```

# Diagrams

```{r}
dummy_data = data_frame(
  x = c(-2, 2),
  y = c(-2, 2)
)

circle_data_f = function(cx, cy, r, n = 1e2) {
  data_frame(
    theta = seq(0, 2 * pi, length.out = n),
    x = cx + r * cos(theta),
    y = cy + r * sin(theta)
  )
}

circle_data = bind_rows(
  circle_data_f(-1, 0, 0.5) %>% mutate(fill = 'white'),
  circle_data_f(1, 0, 0.5) %>% mutate(fill = 'black')
)

line_data = data_frame(
  x = c(-1, -1, 1, 0),
  xend = c(1, -1, 1, 0),
  y = 1.0 * c(0, 1, 1, -1),
  yend = c(0, 0, 0, 0),
  linetype = c('a', rep('b', 3))
)

label_data = data_frame(
  x = c(-1, 1, 0),
  y = 1.4 * c(1, 1, -1),
  label = c('intervention\npopulation', 'control\npopulation', 'interaction\nstrength')
)

twopop_diagram = ggplot(data = NULL, aes(x, y)) +
  geom_blank(data = dummy_data) +
  geom_segment(data = line_data, aes(xend = xend, yend = yend, linetype = linetype)) +
  geom_text(data = label_data, aes(label = label), size = 3) +
  geom_polygon(data= circle_data, aes(fill = fill), color = 'black') +
  scale_fill_manual(values = c('white', 'black')) +
  guides(fill = 'none', linetype = 'none') +
  coord_fixed() +
  theme_void()

twopop_diagram
```

# Within-host neutral (WHN) model

```{r whn_parameters}
whn_base_parms = list(
  beta = 4.0,
  u = 1.0,
  cost = 0.1683543
)

whn_base_parms %>%
  as_tibble() %>%
  kable(caption = 'WHN model parameters')
```

## WHN single-population model

```{r whn_sim}
# vector to data frame
whn_unpack = function(x) {
  matrix(x, ncol = 4) %>%
    as_tibble() %>%
    setNames(c('X', 'S', 'R', 'D'))
}

# data frame to vector
whn_pack = function(df) {
  stopifnot(names(df) == c('X', 'S', 'R', 'D'))
  unlist(df)
}

whn_ode_func = function(t, state_vector, parms) {
  state = whn_unpack(state_vector)

  with(c(state, parms), {
    n_pop = nrow(state)
    stopifnot(dim(betaij) == rep(n_pop, 2))

    N = X + S + R + D

    dS = (betaij %*% ((S + D) / N)) * X - (u + taui) * S - (1 - cost) * (betaij %*% (R / N)) * S
    dR = (1 - cost) * (betaij %*% (R / N)) * X - u * R + taui * D
    dD = (1 - cost) * (betaij %*% (R / N)) * S - (u + taui) * D
    dX = -(dS + dR + dD)

    list(c(dX, dS, dR, dD))
  })
}

whn_sim = function(taui, epsilon) {
  n_pop = length(taui)

  parms = with(whn_base_parms, {
    betaij = matrix(beta * epsilon / n_pop, ncol = n_pop, nrow = n_pop)
    diag(betaij) <- beta * (1 - epsilon * (1 - 1 / n_pop))

    stopifnot(all(rowSums(betaij) == beta))
    stopifnot(all(colSums(betaij) == beta))

    c(whn_base_parms, list(
      taui = taui, epsilon = epsilon,
      betaij = betaij
    ))
  })

  state = data_frame(
    X = rep(0.990 / n_pop, n_pop),
    S = rep(0.005 / n_pop, n_pop),
    R = S,
    D = 0
  )

  state_vector = whn_pack(state)

  result = rootSolve::runsteady(state_vector, func = whn_ode_func, parms = parms)

  result$y %>%
    whn_unpack() %>%
    mutate(
      tau = taui,
      pop = seq_along(taui),
      rho = R / (S + R + D)
    )
}
```

First, I reproduce the $k = 1$ line in Davies *et al.* Figure 2g.

```{r davies_repro}
whn_repro = whn_sim(taui = seq(0, 3 / 12, length.out = 16), epsilon = 0.0)

whn_repro %>%
  ggplot(aes(tau, rho)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(
    name = 'antibiotic tx per month',
    sec.axis = sec_axis(~ . * 12)
  ) +
  ylab('proportion resistant')
```

## WHN two-population model

```{r whn_double}
whn2 <- tibble(
  delta_tau = seq(0, 0.1, length.out = 10),
  taui = map(delta_tau, ~ 0.10 + c(-1, 1) * .)
) %>%
  crossing(epsilon = seq(0, 1, length.out = 20)) %>%
  mutate(results = map2(taui, epsilon, whn_sim))
```

```{r whn2_results}
whn2 %>%
  mutate(delta_rho = map_dbl(results, ~ max(.$rho) - min(.$rho))) %>%
  mutate(drdu = delta_rho / delta_tau) %>%
  filter(is.finite(drdu)) %>%
  ggplot(aes(epsilon, drdu)) +
  geom_point() +
  geom_blank(data = tibble(epsilon = 0, drdu = 0)) +
  xlab('interaction strength') +
  ylab('dr / dr') +
  ggtitle('Two-population model')
```

```{r whn_double_results}
whn2_plot_f = function(df) {
  df %>%
  mutate_at('pop', factor) %>%
  ggplot(aes(x = factor(epsilon), y = rho, fill = pop)) +
  geom_col(position = 'dodge', color = 'black') +
  scale_fill_manual(
    name = '',
    labels = c('intervention', 'control'),
    values = c('white', 'black')
  ) +
  scale_x_discrete(name = expression('interaction strength ' (epsilon))) +
  scale_y_continuous(
    name = 'resistance (%)',
    labels = scales::percent_format(accuracy = 1, suffix = ''),
    limits = c(0, 1.0),
    expand = c(0, 0)
  ) +
  theme_classic() +
  theme(
    axis.title = element_text(size = 9),
    axis.text = element_text(size = 9, color = 'black'),
    legend.text = element_text(size = 9, color = 'black'),
    legend.key.size = unit(4, 'mm'),
    legend.background = element_blank(),
    legend.position = c(0.7, 1.0),
    axis.ticks.x = element_blank(),
    axis.title.x = element_text(size = 9, color = 'black')
  )
}

whn2_plot_data = whn2 %>%
  unnest() %>%
  filter(epsilon %in% c(0.01, 0.10, 0.50)) %>%
  group_by(epsilon, size) %>%
  mutate(delta_tau = round(max(tau) - min(tau), 2)) %>%
  ungroup()

whn2_plot1 = whn2_plot_data %>%
  filter(delta_tau == 0.05) %>%
  whn2_plot_f()

whn2_plot2 = whn2_plot_data %>%
  filter(delta_tau == 0.15) %>%
  whn2_plot_f()

whn2_plot = egg::ggarrange(
  twopop_diagram, whn2_plot1, whn2_plot2,
  nrow = 1,
  labels = letters[1:3]
  #heights = c(0.5, 1, 1)
)

ggsave(
  'fig/whn2_plot.pdf', whn2_plot,
  width = 190, height = 80, unit = 'mm'
)
```


# D-types model

```{r dtypes_parameters}
dtypes_base_parms = list(
  n_d = 16,
  min_mu = 0.5,
  max_mu = 2.0,
  beta = 2.0,
  c_beta = 1.0,
  c_mu = 1.1,
  k = 15.0
)

dtypes_base_parms %>%
  as_tibble() %>%
  kable(caption = 'D-types base parameters')

dtypes_base_parms$mu_d = with(dtypes_base_parms,
                             seq(min_mu, max_mu, length = n_d))

dtypes_base_parms %$%
  data_frame(
    d = 1:n_d,
    mu_d = mu_d
  ) %>%
  kable(caption = 'D-types mu_d values')
```

## Single-population model

```{r dtype_helpers}
# pack the list into a vector
dtypes_pack = function(lst) {
  stopifnot(setequal(names(lst), c('X_i', 'S_id', 'R_id')))
  stopifnot(all(dim(lst$S_id) == dim(lst$R_id)))
  stopifnot(dim(lst$S_id)[1] == length(lst$X_i))
  c(lst$X_i, as.vector(lst$S_id), as.vector(lst$R_id))
}

# unpack the vector into a list
dtypes_unpack = function(x, n_pop, n_d) {
  stopifnot(length(x) == n_pop + 2 * (n_d * n_pop))

  x_end = n_pop
  s_start = x_end + 1
  s_end = x_end + n_d * n_pop
  r_start = s_end + 1
  r_end = s_end + n_d * n_pop
  stopifnot(r_end == length(x))

  list(X_i = x[1:x_end],
       S_id = matrix(x[s_start:s_end], nrow = n_pop, ncol = n_d),
       R_id = matrix(x[r_start:r_end], nrow = n_pop, ncol = n_d))
}

# for initially packing the data frame into the list
dtypes_df_to_list = function(df) {
  # check we have the right column names
  stopifnot(setequal(names(df), c('population', 'phenotype', 'dtype', 'value')))
  # check we have the right phenotypes
  stopifnot(setequal(df$phenotype, c('S', 'R', 'X')))

  # extract the no. populations and D-types
  n_pop = length(unique(df$population))
  n_d = length(unique(df$dtype))

  # there should be S and R for each pop/D-type combo
  stopifnot(nrow(filter(df, phenotype == 'S')) == n_pop * n_d)
  stopifnot(nrow(filter(df, phenotype == 'R')) == n_pop * n_d)
  # but X for only each pop
  stopifnot(nrow(filter(df, phenotype == 'X')) == n_pop)

  list(X_i = df %>% filter(phenotype == 'X') %$% values,
       S_id = df %>% filter(phenotype == 'S') %$% value %>% matrix(nrow = n_pop, ncol = n_d),
       R_id = df %>% filter(phenotype == 'R') %$% value %>% matrix(nrow = n_pop, ncol = n_d))
}

# for finally unpacking the list into a data frame
dtypes_list_to_df = function(lst) {
  # check for names
  stopifnot(setequal(names(lst), c('X_i', 'S_id', 'R_id')))

  # get dimensions
  n_pop = length(lst$X_i)
  n_d = dim(lst$S_id)[2]

  # check shapes
  stopifnot(all(dim(lst$S_id) == c(n_pop, n_d)))
  stopifnot(all(dim(lst$R_id) == c(n_pop, n_d)))

  X_rows = data_frame(pop = 1:n_pop, phenotype = 'X', dtype = NA, value = lst$X_i)
  S_rows = crossing(dtype = 1:n_d, pop = 1:n_pop) %>%
    mutate(phenotype = 'S', value = as.vector(lst$S_id))
  R_rows = crossing(dtype = 1:n_d, pop = 1:n_pop) %>%
    mutate(phenotype = 'R', value = as.vector(lst$R_id))

  bind_rows(X_rows, S_rows, R_rows) %>%
    arrange(pop, phenotype, dtype)
}
```

```{r dtypes_sim}
dtypes_ode_func = function(t, state_vector, parms) {
  state = dtypes_unpack(state_vector, n_pop = parms$n_pop, n_d = parms$n_d)

  with(c(state, parms), {
    stopifnot(length(X_i) == n_pop)
    stopifnot(dim(S_id) == c(n_pop, n_d))
    stopifnot(dim(R_id) == c(n_pop, n_d))

    # rowSums are over D-types (second index)
    v_id = (1.0 - ((S_id + R_id) / rowSums(S_id + R_id) - 1.0 / n_d)) ** k
    stopifnot(dim(v_id) == c(n_pop, n_d))

    N_i = X_i + rowSums(S_id + R_id)
    stopifnot(length(N_i) == n_pop)

    # "tau_i * S_id" does sum_i { tau_i S_id }, which is length P vector
    # to multiply by rows, need to do some fancy footwork: "mat %*% diag(row)"
    dS_id = v_id * (beta_ij %*% (S_id / N_i)) * X_i - tau_i * S_id - S_id %*% diag(mu_d)
    dR_id = v_id * (beta_ij %*% (R_id / N_i)) * X_i - c_mu * R_id %*% diag(mu_d)
    dX_i = -rowSums(dS_id + dR_id)

    list(dtypes_pack(list(X_i = dX_i, S_id = dS_id, R_id = dR_id)))
  })
}

dtypes_sim = function(tau_i, epsilon = 0) {
  n_pop = length(tau_i)

  parms = with(dtypes_base_parms, {
    beta_ij = matrix(beta * epsilon / n_pop, ncol = n_pop, nrow = n_pop)
    diag(beta_ij) <- beta * (1 - epsilon * (1 - 1 / n_pop))

    stopifnot(all(rowSums(beta_ij) == beta))
    stopifnot(all(colSums(beta_ij) == beta))

    c(dtypes_base_parms, list(
      n_pop = n_pop, tau_i = tau_i, epsilon = epsilon, beta_ij = beta_ij
    ))
  })

  n_d = parms$n_d

  state = list(X_i = rep(0.9 / n_pop, n_pop),
               S_id = matrix(0.05 / (n_pop * n_d), nrow = n_pop, ncol = n_d),
               R_id = matrix(0.05 / (n_pop * n_d), nrow = n_pop, ncol = n_d))

  state_vector = dtypes_pack(state)
  stopifnot(all.equal(sum(state_vector), 1))

  result = rootSolve::runsteady(state_vector, func = dtypes_ode_func, parms = parms,
                                stol = 1e-8 / n_pop, rtol = 1e-6 / n_pop, atol = 1e-6 / n_pop)

  result$y %>%
    dtypes_unpack(n_pop = n_pop, n_d = n_d) %>%
    dtypes_list_to_df() %>%
    left_join(data_frame(pop = 1:n_pop, tau = tau_i), by = 'pop')
}
```

First, I reproduce Figure 3 with $\tau = 0.075$.

```{r dtypes_repro_bars}
dtype_repro_bars = dtypes_sim(0.075, 0)

dtype_repro_bars %>%
  mutate(mu_d = dtypes_base_parms$mu_d[dtype]) %>%
  ggplot(aes(mu_d, value, fill = phenotype)) +
  geom_col() +
  xlab('Clearance rate') +
  ylab('Strain prevalence')
```

Next, I show the jagged line in Figure 4. It may not look exactly right because I ran a limited number of simulations:

```{r dtypes_repro_line}
dtype_repro_line = dtypes_sim(seq(0.04, 0.20, length.out = 50), 0)

dtype_repro_line %>%
  group_by(tau) %>%
  summarize(f_res = sum(value[phenotype == 'R']),
            f_all = sum(value)) %>%
  mutate(rho = f_res / f_all) %>%
  ggplot(aes(tau, rho)) +
  geom_point() +
  geom_line()
```

## D-types two-population

```{r dtypes_double}
dtypes2 = twopop_taui_df %>%
  crossing(epsilon = c(0, 0.01, 0.1, 0.25, 0.5, 1.0)) %>%
  mutate(results = map2(taui, epsilon, dtypes_sim))
```

```{r dtypes_double_results}
dtypes_simplify_results = function(df) {
  df %>%
    group_by(pop, phenotype) %>%
    summarize(
      value = sum(value),
      tau = unique(tau)
    ) %>%
    ungroup() %>%
    spread(phenotype, value) %>%
    mutate(rho = R / (R + S))
}

dtypes2_plot = dtypes2 %>%
  mutate(results = map(results, dtypes_simplify_results)) %>%
  unnest() %>%
  group_by(epsilon, size) %>%
  mutate(delta_tau = max(tau) - min(tau)) %>%
  ungroup() %>%
  filter(epsilon %in% c(0.01, 0.10, 0.50)) %>%
  mutate_at('pop', factor) %>%
  ggplot(aes(x = factor(epsilon), y = rho, fill = pop)) +
  facet_grid(
    rows = vars(delta_tau),
    labeller = label_bquote(Delta * tau == .(delta_tau))
  ) +
  geom_col(position = 'dodge', color = 'black') +
  geom_hline(yintercept = 0) +
  scale_fill_manual(
    name = '',
    labels = c('intervention', 'control'),
    values = c('white', 'black')
  ) +
  scale_x_discrete(name = expression('interaction strength ' (epsilon))) +
  scale_y_continuous(
    name = 'resistance (% of hosts)',
    labels = scales::percent_format(accuracy = 1, suffix = ''),
    limits = c(0, 1.0),
    expand = c(0, 0)
  ) +
  theme_classic() +
  theme(
    axis.title = element_text(size = 8),
    axis.text = element_text(size = 8, color = 'black'),
    panel.spacing = unit(6, 'mm'),
    legend.text = element_text(size = 8, color = 'black'),
    legend.key.size = unit(4, 'mm'),
    legend.background = element_blank(),
    legend.position = c(0.7, 1.0),
    strip.background = element_blank(),
    strip.text = element_text(size = 8, color = 'black', face = 'bold'),
    axis.ticks.x = element_blank(),
    axis.title.x = element_text(size = 8, color = 'black'),
    axis.title.y.right = element_text(size = 8, color = 'black', angle = -90)
  )

show(dtypes2_plot)

ggsave(
  'fig/dtypes2_plot.pdf', dtypes2_plot,
  width = 88, height = 80, unit = 'mm'
)
```

