MODELS = ["whn", "dtypes"]
SIMS = ["2pop", "commuting"]

rule all:
    input:
        expand("fig/{model}_2pop.pdf", model=MODELS),
        "results/power.tsv"

# rule tables:
#     pass

rule fig:
    output: expand("fig/{{model}}_{sim}.pdf", sim=SIMS)
    input: expand("results/{{model}}_{sim}.rds", sim=SIMS), "utils.R", script="{model}_figs.R"
    shell: "./{input.script}"

rule sim:
    output: expand("results/{{model}}_{sim}.rds", sim=SIMS)
    input: "{model}_model.R", "utils.R", script="{model}_sims.R"
    shell: "./{input.script}"

rule power:
    output: "results/power.tsv"
    input: "power.R"
    shell: "./{input}"
